### ISSUE TITLE
メール文面実装

### ISSUE THREAD

**Issue by shunyokota** [egg-system/olive-back#75]

**Comment by shunyokota** [comment]
予約確定メール　オリーブボディケア
「タイトル」
ご予約の確認メール

「本文」
高橋 様
ご予約ID：9
予約日時：2019年 06月 11日 10時 00分

女性専門の治療院オリーヴボディケア たまプラーザ店でございます。
この度はご予約いただきありがとうございました。

こちらのメール配信をもちましてご予約確定とさせて頂きます。

高橋様のご来院を心よりお待ちしております。
お気をつけてお越しくださいませ。

当院はメディカルモールたまプラーザの3階301号室となります。
エレベーターに乗る前に1階歯医者さん（こうづま歯科）目の前にインターホンがございますので301→呼出を押して下さい。
当院スタッフが応答致しますので、その後エレベーターへお進みください。

初診の患者様には問診票などのご記入がございますので5分ほど前にお越しください。
前に患者様がいらっしゃいますので早く来られすぎると中に入れない場合がございますので5分前にお願いいたします。

着替えをご用意していますので、ご来院の際はどんな服装でも大丈夫です。
その他ご不明な点ございましたらお気軽にお問い合わせくださいませ。


以下に当院についてのご案内を添付させて頂きます。
URLをクリック（タッチ）してご利用くださいませ。


来院・アクセスについての詳しいご案内はこちら
http://olivejapan.sixcore.jp/access/

Q&A-良くある質問-はこちら
http://olivejapan.sixcore.jp/qa/

当日の施術の流れはこちら
http://olivejapan.sixcore.jp/flow-of-treatment/

『ご注意』
・ご予約確定後の前日・当日キャンセル、無断キャンセルについては、キャンセル料金を頂戴いたします（前日3,240円、当日6,480円）。予めご了承ください。
・ご予約のご変更、キャンセルをご希望の際はご予約日前々日までに当院にご連絡ください。
・仮予約等での複数の予約取得行為は禁止とさせて頂きます。そのご予約は無効となる場合がございます。

女性専門の治療院オリーヴボディケア たまプラーザ店

横浜市青葉区新石川3-15-16 メディカルモールたまプラーザ301
TEL: 045-530-1688
E-Mail: gaku.machida@gmail.com
Webサイト: https://olivebodycare.jp

**Comment by shunyokota** [comment]
**予約確定メール　Simplest**
**タイトル**
ご予約の確認メール

**本文**
高橋 様
ご予約ID：10
予約日時：2019年 06月 13日 11時 00分

Simpleste たまプラーザのエステでございます。
この度はご予約いただきありがとうございました。

こちらのメール配信をもちましてご予約確定とさせて頂きます。

高橋様のご来院を心よりお待ちしております。
お気をつけてお越しくださいませ。

当サロンはメディカルモールたまプラーザの4階402号室となります。
エレベーターに乗る前に1階歯医者さん（こうづま歯科）目の前にインターホンがございますので402→呼出を押して下さい。
当サロンスタッフが応答致しますので、その後エレベーターへお進みください。

前にお客様がいらっしゃいますので早く来られすぎると中に入れない場合がございますので5分前にお願いいたします。

着替えをご用意していますので、ご来店の際はどんな服装でも大丈夫です。
その他ご不明な点ございましたらお気軽にお問い合わせくださいませ。

高橋様のご来店を心よりお待ちしております。
お気をつけてお越しくださいませ。


以下に当サロンについてのご案内を添付させて頂きます。
URLをクリック（タッチ）してご利用くださいませ。


来院・アクセスについての詳しいご案内はこちら
https://simpleste.jp/access/

Web予約キャンセルの手順
https://simpleste.jp/member/cancellation-procedure/

Q&A-良くある質問-はこちら
https://simpleste.jp/qa/

当日の施術の流れはこちら
https://simpleste.jp/service-flow/

『ご注意』
・ご予約確定後の前日・当日キャンセル、無断キャンセルについては、キャンセル料金を頂戴いたします（前日3,240円、当日6,480円）。予めご了承ください。
・ご予約のご変更、キャンセルをご希望の際はご予約日前々日までに当サロンにご連絡ください。
・仮予約等での複数の予約取得行為は禁止とさせて頂きます。そのご予約は無効となる場合がございます。

Simpleste たまプラーザのエステ

横浜市青葉区新石川3-15-16　メディカルモールたまプラーザ301
TEL: 045-530-3966
E-Mail: simpleste.olivejapan@gmail.com
Webサイト: https://simpleste.jp

**Comment by shunyokota** [comment]
**予約キャンセルメール**
**タイトル**
ご予約のキャンセル

**本文**
高橋 様

Simpleste たまプラーザのエステをご利用いただき誠にありがとうございます。

下記ご予約のキャンセルが完了いたしました。

ご予約ID：7
予約日時：2019年 06月 13日 10時 00分
予約したメニュー：上半身メインコース

またのご来店をスタッフ一同心よりお待ちしております。

Simpleste たまプラーザのエステ
〒100-0001
横浜市青葉区新石川3-15-16　メディカルモールたまプラーザ301
TEL: 045-530-3966
E-Mail: simpleste.olivejapan@gmail.com
Webサイト: https://simpleste.jp

**Comment by shunyokota** [comment]
**会員登録メール**
**タイトル**
オリーブボディケア ユーザー登録完了のお知らせ

**本文**
横田 峻 様

オリーブボディケアにユーザー登録して頂きありがとうございます。

こちらでお客様の予約内容をご確認する事ができます。
ログインの際には、ご登録いただいたメールアドレス・パスワードをご入力ください。
https://reserve.olivebodycare.healthcare/mypage

整体・骨盤矯正の女性専門の治療院オリーヴボディケア
TEL：045-530-1688（たまプラーザ本店）
E-Mail：info@olivebodycare.jp
Webサイト：https://olivebodycare.healthcare/
治療院一覧：https://olivebodycare.healthcare/salon
　・たまプラーザ本店：https://olivebodycare.healthcare/salon/tamaplaza
　・横浜青葉台店：https://olivebodycare.healthcare/salon/aobadai

**Comment by shunyokota** [comment]
**パスワードリセットメール**
**タイトル**
女性専門の治療院オリーヴボディケアのパスワードのリセット

**本文**
女性専門の治療院オリーヴボディケアのパスワードのリセットを受け付けました。

こちらのページから新しいパスワードの登録を行ってください。
http://localhost:8080/api/customers/password/edit?config=default&redirect_url=http%3A%2F%2Flocalhost%3A3000%2Fpassword%2Fset&reset_password_token=9VYKURPSEwGtVte5VFSL

整体・骨盤矯正の女性専門の治療院オリーヴボディケア
TEL：045-530-1688（たまプラーザ本店）
E-Mail：info@olivebodycare.jp
Webサイト：https://olivebodycare.healthcare/
治療院一覧：https://olivebodycare.healthcare/salon
　・たまプラーザ本店：https://olivebodycare.healthcare/salon/tamaplaza
　・横浜青葉台店：https://olivebodycare.healthcare/salon/aobadai

**Comment by nuno929** [comment]
解決済み
